[tox]
envlist = linters
skipsdist = true

[testenv:linters]
deps =
    black
    flake8
    isort
skip_install = true
commands =
    black --check {posargs:plugins/ tests/}
    flake8 {posargs:plugins/ tests/}
    isort --check {posargs:plugins/ tests/}

[testenv:black]
deps = black
skip_install = true
commands = black {posargs:plugins/ tests/}

[testenv:flake8]
deps = flake8
skip_install = true
commands = flake8 {posargs:plugins/ tests/}

[testenv:isort]
deps = isort
skip_install = true
commands = isort {posargs:plugins/ tests/}

[black]
line-length = 160
fast = true
skip-string-normalization = true
force-exclude =
    (
       .*/migrations/
     | .*/__pycache__/
     | .tox/
     | .pytest_cache/
     | build/
     | dist/
     | *.egg-info/
    )

[flake8]
max-line-length = 160
extend-ignore = E203, E402, F841, DOC
exclude =
    .tox,
    .pytest_cache,
    __pycache__,
    *.egg-info,
    build,
    dist,
    .git,
    .github,
    .mypy_cache,
    .venv,
    venv,
    __init__.py
per-file-ignores =
    plugins/modules/*:E402
    tests/**.py:S101
count = true
statistics = true
